### PR TITLE
Get rid of vulcan dependency and recompile for both cedar and cedar-14 stacks

### PR DESCRIPTION
**Pull request by benalavi**

### CODE REVIEW

**Comment by benalavi** [comment]
Fixes #8, works w/ cedar & cedar-14 using Heroku STACK environment variable (https://devcenter.heroku.com/articles/buildpack-api#stacks) -- both builds will need to be compiled uploaded into the heroku-buildpacks-graphicsmagick bucket first due to the way it expects paths to be set up.

Can compile using VMs defined in Vagrantfile or on heroku using `heroku run bash` on a new cedar and cedar-14 stack.

The VM setup was helpful to me to more easily fix the issue, no problem to get rid of it.

**Comment by mcollina** [comment]
Can you please update the build instruction section, so that everybody knows how to build things?

Also, update the README and flag this as an OPEN Open Source module, if @paolochiodi is ok too.
Follow this example (https://github.com/rvagg/node-levelup) and (https://github.com/mqttjs/MQTT.js).

I will send you an email with an IAM account that can be used to push to the main S3 repo.

**Comment by mcollina** [comment]
Also, write somewhere that you are the lead maintainer of this thing :)

**Comment by paolochiodi** [comment]
:+1: 

Thank you @benalavi

**Comment by benalavi** [comment]
@mcollina @paolochiodi Sorry for the delay, been a busy week! Updated the README, merged this and verified that buildpack is now working on both cedar and cedar-14, will clean up the related issues.

**Comment by mcollina** [comment]
Thanks so much!! :dancers:

**Pull request merged**
